change binary name

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -80,7 +80,7 @@ jobs:
     - name: Confirm broker binary exists
       run: |
         ls -alh ./target/release/
-        test -x ./target/release/serverless_kafka_broker || (echo "❌ Binary not found!" && exit 1)
+        test -x ./target/release/stateless_kafka_broker || (echo "❌ Binary not found!" && exit 1)
       working-directory: ${{ github.workspace }}
 
 
@@ -100,7 +100,7 @@ jobs:
         KAFKA_INDEX_STORE_TYPE: redis
         KAFKA_INDEX_STORE_REDIS_URL: redis://localhost:6379
       run: |
-        ./target/release/serverless_kafka_broker --config config/cluster.sample.json 2>&1 | tee rust-server.log &
+        ./target/release/stateless_kafka_broker --config config/cluster.sample.json 2>&1 | tee rust-server.log &
       working-directory: ${{ github.workspace }}
 
     - name: Wait for Rust server to be ready
