debug binary path

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -77,6 +77,13 @@ jobs:
     - name: Build broker
       run: cargo build --release
 
+    - name: Confirm broker binary exists
+      run: |
+        ls -alh ./target/release/
+        test -x ./target/release/serverless_kafka_broker || (echo "❌ Binary not found!" && exit 1)
+      working-directory: ${{ github.workspace }}
+
+
     - name: Run Rust server in background
       env:
         RUST_LOG: debug
@@ -94,6 +101,7 @@ jobs:
         KAFKA_INDEX_STORE_REDIS_URL: redis://localhost:6379
       run: |
         ./target/release/serverless_kafka_broker 2>&1 | tee rust-server.log &
+      working-directory: ${{ github.workspace }}
 
     - name: Wait for Rust server to be ready
       run: |
